%%% @doc Prototype docs renderer device for HyperBEAM `/info' pages.
%%%
%%% The shared docs object is generated by `hb_docs'. This device gives that
%%% renderer a protocol-native device surface so the prototype is not just a
%%% meta-device special case.
-module(dev_cookbook).
-implements(<<"cookbook@1.0">>).
-export([info/1, info/3]).
-export([index/3, node/3, device/3, schema/3, spec/3, recipes/3]).

-define(DEFAULT_DEVICE, <<"message@1.0">>).

info(_Opts) ->
    #{
        exports => [
            <<"info">>,
            <<"index">>,
            <<"node">>,
            <<"device">>,
            <<"schema">>,
            <<"spec">>,
            <<"recipes">>
        ]
    }.

%% @doc Return docs for the cookbook renderer itself.
info(_Base, Req, Opts) ->
    hb_docs:device_info(<<"cookbook@1.0">>, Req, Opts).

%% @doc Render the node documentation index.
index(_Base, Req, Opts) ->
    hb_docs:node_info(Req, Opts).

%% @doc Alias for `index/3'.
node(Base, Req, Opts) ->
    index(Base, Req, Opts).

%% @doc Render documentation for the device named in the `for' parameter.
device(_Base, Req, Opts) ->
    hb_docs:device_info(requested_device(Req, Opts), Req, Opts).

%% @doc Render schema for the device named in the `for' parameter.
schema(_Base, Req, Opts) ->
    hb_docs:device_info_route(requested_device(Req, Opts), [<<"schema">>], Req, Opts).

%% @doc Render spec for the device named in the `for' parameter.
spec(_Base, Req, Opts) ->
    hb_docs:device_info_route(requested_device(Req, Opts), [<<"spec">>], Req, Opts).

%% @doc Render recipes for the device named in the `for' parameter.
recipes(_Base, Req, Opts) ->
    hb_docs:device_info_route(requested_device(Req, Opts), [<<"recipes">>], Req, Opts).

requested_device(Req, Opts) ->
    strip_device_prefix(
        hb_maps:get(
            <<"for">>,
            Req,
            hb_maps:get(<<"device-id">>, Req, ?DEFAULT_DEVICE, Opts),
            Opts
        )
    ).

strip_device_prefix(<<"~", Device/binary>>) ->
    Device;
strip_device_prefix(Device) ->
    Device.
